services:
  nginx:
    image: nginx:alpine
    ports:
      - '8080:8080'
    volumes:
      - ./infra/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  postgres:
    image: postgres:15-alpine
    container_name: hotzla-postgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: hotzla_user
      POSTGRES_PASSWORD: hotzla_password
      POSTGRES_DB: hotzla_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
