export const OrderStatus = {
  PENDING_BUDGET: 'PENDING_BUDGET',
  PENDING_MANAGER_APPROVAL: 'PENDING_MANAGER_APPROVAL',
  APPROVED_FOR_PRODUCTION: 'APPROVED_FOR_PRODUCTION',
  IN_PRODUCTION: 'IN_PRODUCTION',
  READY_FOR_PICKUP: 'READY_FOR_PICKUP',
  COMPLETED: 'COMPLETED',
  REJECTED_BUDGET: 'REJECTED_BUDGET',
  REJECTED_MANAGER: 'REJECTED_MANAGER',
  CANCELLED: 'CANCELLED',
} as const;

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

export const ALLOWED_ORDER_STATUS_TRANSITIONS: Record<OrderStatus, readonly OrderStatus[]> = {
  PENDING_BUDGET: ['PENDING_MANAGER_APPROVAL', 'REJECTED_BUDGET', 'CANCELLED'],

  PENDING_MANAGER_APPROVAL: ['APPROVED_FOR_PRODUCTION', 'REJECTED_MANAGER'],

  APPROVED_FOR_PRODUCTION: ['IN_PRODUCTION'],

  IN_PRODUCTION: ['READY_FOR_PICKUP'],

  READY_FOR_PICKUP: ['COMPLETED'],

  COMPLETED: [],
  REJECTED_BUDGET: [],
  REJECTED_MANAGER: [],
  CANCELLED: [],
};

export const isOrderStatusTransitionAllowed = (
  fromStatus: OrderStatus,
  toStatus: OrderStatus
): boolean => ALLOWED_ORDER_STATUS_TRANSITIONS[fromStatus].includes(toStatus);
